### ISSUE TITLE
Syntax Error in DynamicFieldAction.php file (line 10)

### ISSUE THREAD

**Issue by twyzle** [tunezilla/nova-dynamic-action-fields#2]
Php is throwing the following error when running without changes

syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) {"userId":99,"exception":"[object] (ParseError(code: 0): syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) at /private/var/www/html/example-project/vendor/tunezilla/dynamic-action-fields/src/DynamicFieldAction.php:10)
[stacktrace]

This is the line causing the problem 

public ?ActionRequest $actionRequest = null;

When I replace with the following 

public function __construct(ActionRequest $actionRequest = null)
    {
    }

it works as expected. 

Note:: error occurred running php 7.3.8. on 7.4.1 code ran without problem without the change

**Comment by tunezilla** [comment]
Hello @twyzle,

Thank you for reporting this. The information about your PHP versions was helpful.

Even though our composer.json stated support for PHP 7.1+, we used the typed class properties feature from PHP 7.4: https://www.php.net/manual/en/migration74.new-features.php

![image](https://user-images.githubusercontent.com/60528913/148261499-ece0b36a-1eeb-410a-b7a3-8d2ce4bb2ec2.png)

I've replaced this with PHP 7.1-compatible code:

```diff
diff --git a/src/DynamicFieldAction.php b/src/DynamicFieldAction.php
index 21b9e3e..f99adda 100644
--- a/src/DynamicFieldAction.php
+++ b/src/DynamicFieldAction.php
@@ -7,7 +7,8 @@ use Laravel\Nova\Http\Requests\ActionRequest;
 
 trait DynamicFieldAction
 {
-    public ?ActionRequest $actionRequest = null;
+    /** @var ActionRequest|null */
+    public $actionRequest = null;
 
     final public function component()
     {
```

and published it as version 1.0.1: https://packagist.org/packages/tunezilla/dynamic-action-fields#v1.0.1

Cheers!
