### ISSUE TITLE
All matching(N) do not use choosing filters

### ISSUE THREAD

**Issue by sashagar** [tunezilla/nova-dynamic-action-fields#4]
Problem: if you apply any filters for resources and choose All matching(N) in result you see Action window for all resources without filters.

https://github.com/tunezilla/nova-dynamic-action-fields/blob/dff9798e2ed13499f09ccb5d50b083b8089ab0d3/src/DynamicFieldAction.php#L28 ignore filters

**Comment by tunezilla** [comment]
Hello,

Can you please submit code to reproduce this issue?

Thanks!
